#!/usr/bin/env bash
if [ $# -eq 1 ] 
then
	if [ $1 = "arc" ]
	then
		gdb_tool="/home/jihongbin/tools/arc_gnu_2021.09_prebuilt_elf32_le_linux_install/bin/arc-elf32-gdb"
	elif [ $1 = "gdb" ]
	then
		gdb_tool="gdb"
	fi
else
	gdb_tool="gdb-multiarch"
fi

ARGS=$ARGS\ -x\ ./gdb/gdb.init

echo "use gdb tool ${gdb_tool}"

if [ -z "$TMUX" ]
then
    exec_cmd="exec tmux -T 256 new -n GDB"
else
    exec_cmd="exec tmux -T 256 new-window -n GDB"
fi

$exec_cmd "$gdb_tool -x '~/.gdb/tmux_dashboard_init' $ARGS ; tmux kill-window -t \$TMUX_PANE"
